Добавляет перевод терминов "maintainer" и "contributor"
web-standards-ru/dictionary pull request #431
Opened 2021-05-30 22:16 UTC by myshov

Добавил перевод терминов "maintainer" и "contributor"

closes #430

2021-05-30 22:25 UTC, skip405 commented
А _collaborator_ не хотим в этот список включить? Чтобы два раза не бегать :) Есть ещё _member_, но не уверен, что имеет смысл его добавлять.

2021-05-30 22:39 UTC, myshov commented
@skip405 идея хорошая, но не знаю как его перевести точно. На первый взгляд кажется, что это синоним contributor

2021-05-31 06:38 UTC, skip405 commented
С моей колокольни кажется, что ваше определение подходит скорее для _collaborator_. _Contributor_ получается после принятого пул-реквеста. Там не обязательно оставаться с проектом, писать документацию и всё, что вы перечисляете. Нашёл [список ролей](https://opensource.guide/how-to-contribute/#anatomy-of-an-open-source-project) и [описание collaborator](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization), которые могут помочь в переводе.

2021-05-31 17:14 UTC, myshov commented
Посмотрел список ролей, и у меня закралось сомнение стоит, ли добавлять collaborator (в списке нет этой роли).

Интересно услышать мнение @pepelsbey по этому поводу

2021-05-31 21:54 UTC, pepelsbey commented
Я бы пока добавил только активно употребимые в сообществе роли: контрибьютор и мейнтейнер. Коммиттер, колаборатор и прочие — это уже более мутные роли, которые отличаются от проекта к проекту. А эти две — понятные.

2021-05-31 21:56 UTC, pepelsbey requested changes
Я бы в определениях сфокусировался на опенсорсе и убрал упоминание сообщества. Проект в опенсорсе может быть любым, вокруг не обязательно должно быть сообщество.

Плюс я бы более явно развёл эти роли, чтобы было понятно, кто чем занимается и у кого какие права. Например, [вот такие описания ролей](https://opensource.guide/leadership-and-governance/#what-are-examples-of-formal-roles-used-in-open-source-projects) я нагуглил. Чтобы было понятно:

1. Один только пишет код
2. Другой ещё принимает решения

2021-06-08 15:00 UTC, myshov commented
@pepelsbey исправил определения

2021-06-09 12:45 UTC, pepelsbey approved these changes

2021-06-09 12:45 UTC, merged

2021-06-09 12:46 UTC, pepelsbey commented
Спасибо :)

При желании, можно развить описание примерами, ссылками и подобным в отдельных пулреквестах.

Я решил не затягивать этот ПР ещё больше и смёржил.

2021-06-09 13:33 UTC, myshov commented
Хорошо, буду иметь в виду :)