Добавляет куки
web-standards-ru/dictionary pull request #452
Opened 2022-03-31 12:58 UTC by dekhanov

По сути я просто зафиксировал практику употребления слова куки из русского перевода MDN: https://developer.mozilla.org/ru/docs/Web/HTTP/Cookies

Но там нигде нет употребления и склонения слова "куки" в единственном числе. Тут я зафиксировал практику употребления в моем окружении, так что это момент для дискуссий. Еще не нашел в словаре примеров описания форм слова - как его употреблять в разных склонениях, поэтому просто добавил примеры.

2022-03-31 13:14 UTC, myshov commented on dictionary.md
> +- first-party cookies — **куки первого лица**
Думаю, что лучше перевисти first-party cookies как "собственные куки". Открыл issue в mdn https://github.com/mdn/translated-content/issues/4914 для обсуждения

2022-03-31 13:35 UTC, skip405 commented
А так ли нужно указывать, что фрагмент данных «небольшой»?

2022-03-31 13:43 UTC, dekhanov commented on dictionary.md
> +- first-party cookies — **куки первого лица**
Принял

2022-03-31 13:44 UTC, dekhanov commented
> А так ли нужно указывать, что фрагмент данных «небольшой»?

Определение взял из MDN

2022-03-31 13:49 UTC, skip405 commented
«Отправляемый на браузер» тоже для меня звучит немного странно, именно предлог. Может, правда, это только мне режет)

2022-03-31 13:55 UTC, myshov commented
> «Отправляемый на браузер» тоже для меня звучит немного странно, именно предлог. Может, правда, это только мне режет)

Это косяк перевода в MDN

2022-03-31 14:02 UTC, skip405 commented
Если предлагаемый вариант склоняется, то я статью бы не называл во множественном числе. Извиняюсь, что растягиваю свои мысли на три коротких комментария ))

2022-03-31 22:24 UTC, pepelsbey requested changes
Приглушил справочность и развернул примеры склонений в формате оригинал-перевод.

2022-03-31 22:24 UTC, pepelsbey commented on dictionary.md
> +**куки,** небольшой фрагмент данных, отправляемый сервером и сохраняемый браузером пользователя. Эти данные отправляются обратно с каждым новым запросом к данному серверу. В единственном числе — **ку
```suggestion
**куки,** небольшой фрагмент данных, который отправляется с сервера и сохраняется в браузере. В единственном числе — **кука**. Примеры склонений:

- access to cookies — доступ к кукам
- cookie banner — сообщение о куках
- authorization cookie — авторизационная кука
```

2022-04-03 12:20 UTC, pepelsbey approved these changes
Класс!

2022-04-03 12:20 UTC, merged

2022-04-03 12:21 UTC, pepelsbey commented
Спасибо :)

2022-04-04 07:47 UTC, dekhanov commented
Спасибо всем за ревью!